name: keep-supabase-alive
on:
  schedule:
    - cron: '0 10 8 ? * MON,WED,SUN *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://jiahao.vercel.app/api/keep-supabase-alive'
