name: keep-supabase-alive
on:
  schedule:
    - cron: '42 3 * * 1,3,5'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://jiahao.vercel.app/api/keep-supabase-alive'
